version: "3.8"

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:0.235.0
    restart: always
    ports:
      - "80:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - EXECUTIONS_PROCESS=main
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=Europe/Warsaw
    volumes:
      - ${DATA_FOLDER}:/home/node/.n8n
    command: /bin/sh -c "n8n start"
