version: '3.1'

volumes:
  gitlab-runner-config:

services:
  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    